title: Nokia 3.1 Plus
description: "A  Blog for Nokia 3.1 Plus!"
author:
  name: "zapacitu18"
  email: "drewmeister373@gmail.com"
  url: "3-1Plus.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Nokia 3.1 Plus"
year : "2019"
